server:
  port: 9090

# H2 Database Configuration
spring:
  application:
    name=stugbokningssytem-bff:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2